/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import DBModels.PlayerDAO;
import DBEntities.Admin;
import DBEntities.Player;
import java.awt.Color;
import java.util.ArrayList;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO
 */
public class ChangeProfile extends javax.swing.JDialog {

    private String UserName;
    ArrayList<Player> ds;
    int D, M, Y;
    private Profile profile;

    public ChangeProfile(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        profile = (Profile) parent;
        D = M = Y = 0;

    }
//public void getChange(){
//      UserName = profile.username;
//      
//}

    private boolean checkValid() {

        if (cmbDay.getSelectedIndex() != 0) {
            D = Integer.parseInt(cmbDay.getSelectedItem().toString());
        }
        if (cmbMo.getSelectedIndex() != 0) {
            M = Integer.parseInt(cmbMo.getSelectedItem().toString());
        }
        if (cmbYear.getSelectedIndex() != 0) {
            Y = Integer.parseInt(cmbYear.getSelectedItem().toString());
        }

        Pattern Pm = Pattern.compile("^[a-zA-Z][\\w-]+@([\\w]+\\.[\\w]+|[\\w]+\\.[\\w]{2,}\\.[\\w]{2,})$");
        Matcher mm = Pm.matcher(txtEmail.getText().trim());
        if (!mm.matches()) {
            JOptionPane.showMessageDialog(this, "Email không hợp lệ... ");
            txtEmail.requestFocus();
            return false;
        }
        if (cmbDay.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn ngày sinh ...");
            return false;
        }
        if (cmbMo.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Vui lòng chon tháng sinh...");
            return false;
        }
        if (cmbYear.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "vui  lòng chon năm sinh...");
            return false;
        }

        if ((M == 4 || M == 6 || M == 9 || M == 11) && (D == 31)) {
            JOptionPane.showMessageDialog(this, "Tháng " + cmbMo.getSelectedItem() + " chỉ 30 Ngày");
            return false;
        }
        if (((Y % 4 == 0 && Y % 100 != 0) || (Y % 400 == 0)) && (M == 2 && D >= 29)) {
            JOptionPane.showMessageDialog(this, "Tháng 2 năm nhuận chỉ 28 ngày");
            return false;
        }
        if (M == 2 && D >= 30) {
            JOptionPane.showMessageDialog(this, "Tháng 2 chỉ 29 Ngày");
            return false;
        }
        Pattern p = Pattern.compile("[0-9]{10,12}");
        Matcher m = p.matcher(txtPhone.getText().trim());
        if (!m.matches()) {
            JOptionPane.showMessageDialog(this, "Số điện thoại không được để trống, phải là số và từ 10-12 ký số ... ");
            txtPhone.requestFocus();
            return false;
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        bntChange = new javax.swing.JButton();
        bntCancel1 = new javax.swing.JButton();
        bntReset = new javax.swing.JButton();
        cmbDay = new javax.swing.JComboBox<>();
        cmbMo = new javax.swing.JComboBox<>();
        cmbYear = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ĐỔI THÔNG TIN");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 570, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Số điện thoại:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 160, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Email:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 110, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Ngày tháng năm sinh:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 160, 40));
        jPanel1.add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 360, 40));
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 360, 40));

        bntChange.setBackground(new java.awt.Color(51, 51, 51));
        bntChange.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bntChange.setForeground(new java.awt.Color(255, 255, 255));
        bntChange.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/OK Hand Medium Skin Tone_48px.png"))); // NOI18N
        bntChange.setText("Thay đổi");
        bntChange.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bntChange.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bntChange.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        bntChange.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bntChangeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bntChangeMouseExited(evt);
            }
        });
        bntChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntChangeActionPerformed(evt);
            }
        });
        jPanel1.add(bntChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 160, 50));

        bntCancel1.setBackground(new java.awt.Color(51, 51, 51));
        bntCancel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bntCancel1.setForeground(new java.awt.Color(255, 255, 255));
        bntCancel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel2.png"))); // NOI18N
        bntCancel1.setText("Bỏ qua");
        bntCancel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bntCancel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bntCancel1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        bntCancel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bntCancel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bntCancel1MouseExited(evt);
            }
        });
        bntCancel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntCancel1ActionPerformed(evt);
            }
        });
        jPanel1.add(bntCancel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 340, 160, 50));

        bntReset.setBackground(new java.awt.Color(51, 51, 51));
        bntReset.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bntReset.setForeground(new java.awt.Color(255, 255, 255));
        bntReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reset_48px.png"))); // NOI18N
        bntReset.setText("Đặt lại");
        bntReset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bntReset.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bntReset.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        bntReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bntResetMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bntResetMouseExited(evt);
            }
        });
        bntReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntResetActionPerformed(evt);
            }
        });
        jPanel1.add(bntReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, 160, 50));

        cmbDay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jPanel1.add(cmbDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 100, 40));

        cmbMo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", " ", " " }));
        jPanel1.add(cmbMo, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, 100, 40));

        cmbYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010" }));
        jPanel1.add(cmbYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, 100, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 647, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bntChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntChangeActionPerformed
        // TODO add your handling code here:
        boolean isOK = true;
        Player pl = new Player();
        pl.Name = profile.username;
        pl.Email = txtEmail.getText();
        pl.Phone = txtPhone.getText();
        pl.DOB = cmbDay.getSelectedItem().toString() + "-" + cmbMo.getSelectedItem().toString() + "-" + cmbYear.getSelectedItem().toString();
        ds = PlayerDAO.CheckRegister();
        for (Player item : ds) {

            if (item.getEmail().equals(txtEmail.getText().trim()) && !item.getName().equals(profile.username)) {
                JOptionPane.showMessageDialog(this, "Email này đã tồn tại. Vui lòng nhập lại!!! ");
                txtEmail.requestFocus();
                isOK = false;
                break;
            }
            if (item.getPhone().equals(txtPhone.getText().trim()) && !item.getName().equals(profile.username)) {
                JOptionPane.showMessageDialog(this, "Số điện thoại này đã tồn tại. Vui lòng nhập lại!!! ");
                txtPhone.requestFocus();
                isOK = false;
                break;
            }
        }
        if (isOK == true && checkValid()) {
            int option = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn thay đổi thông tin trên....", "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (option == JOptionPane.YES_OPTION) {
                PlayerDAO.changeProfile(pl);
                JOptionPane.showMessageDialog(this, "Đổi thông tin thành công...");
                profile.Showprofile();
                this.dispose();

            }
        }
    }//GEN-LAST:event_bntChangeActionPerformed

    private void bntCancel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntCancel1MouseEntered
        // TODO add your handling code here:
        ImageIcon close = new ImageIcon("./src/images/cancel_48px.png");
        bntCancel1.setBackground(Color.black);
        bntCancel1.setIcon(close);
    }//GEN-LAST:event_bntCancel1MouseEntered

    private void bntCancel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntCancel1MouseExited
        // TODO add your handling code here:
        ImageIcon close = new ImageIcon("./src/images/cancel2.png");
        bntCancel1.setBackground(new Color(51, 51, 51));
        bntCancel1.setIcon(close);
    }//GEN-LAST:event_bntCancel1MouseExited

    private void bntCancel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntCancel1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_bntCancel1ActionPerformed

    private void bntResetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntResetMouseEntered
        // TODO add your handling code here:
        ImageIcon close = new ImageIcon("./src/images/reset2.png");
        bntReset.setBackground(Color.black);
        bntReset.setIcon(close);
    }//GEN-LAST:event_bntResetMouseEntered

    private void bntResetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntResetMouseExited
        // TODO add your handling code here:
        ImageIcon close = new ImageIcon("./src/images/reset_48px.png");
        bntReset.setBackground(new Color(51, 51, 51));
        bntReset.setIcon(close);
    }//GEN-LAST:event_bntResetMouseExited

    private void bntResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntResetActionPerformed
        txtEmail.setText("");
        txtPhone.setText("");
        cmbYear.setSelectedItem(null);
        cmbDay.setSelectedItem(null);
        cmbMo.setSelectedItem(null);
    }//GEN-LAST:event_bntResetActionPerformed

    private void bntChangeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntChangeMouseEntered
        // TODO add your handling code here:
        ImageIcon close = new ImageIcon("./src/images/OK Hand Light Skin Tone_48px.png");
        bntChange.setBackground(Color.black);
        bntChange.setIcon(close);
    }//GEN-LAST:event_bntChangeMouseEntered

    private void bntChangeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntChangeMouseExited
        // TODO add your handling code here:
        ImageIcon close = new ImageIcon("./src/images/OK Hand Medium Skin Tone_48px.png");
        bntChange.setBackground(new Color(51, 51, 51));
        bntChange.setIcon(close);
    }//GEN-LAST:event_bntChangeMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangeProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangeProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangeProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangeProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ChangeProfile dialog = new ChangeProfile(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntCancel1;
    private javax.swing.JButton bntChange;
    private javax.swing.JButton bntReset;
    public javax.swing.JComboBox<String> cmbDay;
    public javax.swing.JComboBox<String> cmbMo;
    public javax.swing.JComboBox<String> cmbYear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField txtEmail;
    public javax.swing.JTextField txtPhone;
    // End of variables declaration//GEN-END:variables
}
