/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import DBModels.AdminDAO;
import java.awt.Color;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO
 */
public class ChangePass extends javax.swing.JDialog {
   private String UserName;
    private String Password;
     private Admin_page Admins;
    public ChangePass(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
         Admins = (Admin_page) parent;
         jLbTK.setText("Tài khoản: "+Admins.user);
            this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLbTK = new javax.swing.JLabel();
        txtCurrent_Pass = new javax.swing.JPasswordField();
        txtNewPass = new javax.swing.JPasswordField();
        txtConfirmPass = new javax.swing.JPasswordField();
        bntChange = new javax.swing.JButton();
        bntReset = new javax.swing.JButton();
        bntCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Đổi mật khẩu");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 180, 40));

        jLabel1.setBackground(new java.awt.Color(204, 204, 255));
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nhập lại mật khẩu mới:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 220, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText(" Mật khẩu hiện tại :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 180, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Mật khẩu mới:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 180, 40));

        jLbTK.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLbTK.setForeground(new java.awt.Color(255, 255, 0));
        jLbTK.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbTK.setText("Tài khoản:");
        jPanel1.add(jLbTK, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 240, 30));
        jPanel1.add(txtCurrent_Pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 290, 40));
        jPanel1.add(txtNewPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 290, 40));
        jPanel1.add(txtConfirmPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, 290, 40));

        bntChange.setBackground(new java.awt.Color(51, 51, 51));
        bntChange.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bntChange.setForeground(new java.awt.Color(255, 255, 255));
        bntChange.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/OK Hand Medium Skin Tone_48px.png"))); // NOI18N
        bntChange.setText("Thay đổi");
        bntChange.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bntChange.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bntChange.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        bntChange.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bntChangeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bntChangeMouseExited(evt);
            }
        });
        bntChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntChangeActionPerformed(evt);
            }
        });
        jPanel1.add(bntChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 160, 50));

        bntReset.setBackground(new java.awt.Color(51, 51, 51));
        bntReset.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bntReset.setForeground(new java.awt.Color(255, 255, 255));
        bntReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reset_48px.png"))); // NOI18N
        bntReset.setText("Đặt lại");
        bntReset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bntReset.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bntReset.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        bntReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bntResetMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bntResetMouseExited(evt);
            }
        });
        bntReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntResetActionPerformed(evt);
            }
        });
        jPanel1.add(bntReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, 160, 50));

        bntCancel.setBackground(new java.awt.Color(51, 51, 51));
        bntCancel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bntCancel.setForeground(new java.awt.Color(255, 255, 255));
        bntCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel_48px.png"))); // NOI18N
        bntCancel.setText("Bỏ qua");
        bntCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bntCancel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bntCancel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        bntCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bntCancelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bntCancelMouseExited(evt);
            }
        });
        bntCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntCancelActionPerformed(evt);
            }
        });
        jPanel1.add(bntCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 370, 160, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntChangeActionPerformed
        // TODO add your handling code here:
       
        
        boolean check = true;
        String user = Admins.user;
        String current = Admins.pass;
        String newpass = new String(txtNewPass.getPassword());
        String confirmpass = new String(txtConfirmPass.getPassword());
        //1. tao ket noi tu ung dung java den sql server

        if (txtCurrent_Pass.getPassword().length == 0) {
            JOptionPane.showMessageDialog(this, "Mật khẩu hiện tại không được để trống!");
            txtCurrent_Pass.requestFocus();
            check = false;
           return;
        }
        if (!current.equals(new String(txtCurrent_Pass.getPassword()))) {
            JOptionPane.showMessageDialog(this, "Mật khẩu hiện tại không đúng!");
            txtCurrent_Pass.requestFocus();
            check = false;
            return;
        }
        Pattern Pp = Pattern.compile("^[a-zA-Z0-9_-]{13,20}$");
        Matcher mp = Pp.matcher(new String(txtNewPass.getPassword()).trim());
        if (!mp.matches()) {
            JOptionPane.showMessageDialog(this, "Mật khẩu không được để trống và 13-20 ký tự hoặc ký số không chứa ký tự đặc biệt ... ");
            txtNewPass.requestFocus();
            check = false;
        return;
        }
        //         else if (txtNewPass.getPassword().length == 0) {
            //            JOptionPane.showMessageDialog(this, "New Password can't be blank!");
            //            txtNewPass.requestFocus();
            //            check = false;
            //        }
        if (txtConfirmPass.getPassword().length == 0) {
            JOptionPane.showMessageDialog(this, "Vui lòng xác nhận mật khẩu!");
            txtConfirmPass.requestFocus();
            check = false;
            return;
        }
        if (!new String(txtConfirmPass.getPassword()).equals(new String(txtNewPass.getPassword()))) {
            JOptionPane.showMessageDialog(this, "Mật khẩu xác nhận không chính xác!");
            txtConfirmPass.requestFocus();
            check = false;
            return;
        }
        if (newpass.equals(confirmpass) && current.equals(new String(txtCurrent_Pass.getPassword())) && check == true) {
            AdminDAO.changePass(newpass, user);
            JOptionPane.showMessageDialog(this, "Đổi mẩu khẩu thành công!");
           this.dispose();
        }
    }//GEN-LAST:event_bntChangeActionPerformed

    private void bntResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntResetActionPerformed
        // TODO add your handling code here:
        txtNewPass.setText(null);
        txtConfirmPass.setText(null);
        txtCurrent_Pass.setText(null);
    }//GEN-LAST:event_bntResetActionPerformed

    private void bntCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntCancelActionPerformed
        // TODO add your handling code here:
     
        this.dispose();
      
    }//GEN-LAST:event_bntCancelActionPerformed

    private void bntChangeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntChangeMouseEntered
         ImageIcon close = new ImageIcon("./src/images/OK Hand Light Skin Tone_48px.png");
        bntChange.setBackground(Color.black);
        bntChange.setIcon(close);
    }//GEN-LAST:event_bntChangeMouseEntered

    private void bntChangeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntChangeMouseExited
            ImageIcon close = new ImageIcon("./src/images/OK Hand Medium Skin Tone_48px.png");
        bntChange.setBackground(new Color(51,51,51));
        bntChange.setIcon(close);
    }//GEN-LAST:event_bntChangeMouseExited

    private void bntResetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntResetMouseEntered
        // TODO add your handling code here:
            ImageIcon close = new ImageIcon("./src/images/reset2.png");
        bntReset.setBackground(Color.black);
        bntReset.setIcon(close);
    }//GEN-LAST:event_bntResetMouseEntered

    private void bntResetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntResetMouseExited
        // TODO add your handling code here:
          ImageIcon close = new ImageIcon("./src/images/reset_48px.png");
        bntReset.setBackground(new Color(51, 51, 51));
        bntReset.setIcon(close);
    }//GEN-LAST:event_bntResetMouseExited

    private void bntCancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntCancelMouseEntered
        // TODO add your handling code here:
            ImageIcon close = new ImageIcon("./src/images/cancel2.png");
        bntCancel.setBackground(Color.black);
        bntCancel.setIcon(close);
    }//GEN-LAST:event_bntCancelMouseEntered

    private void bntCancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntCancelMouseExited
        // TODO add your handling code here:
            ImageIcon close = new ImageIcon("./src/images/cancel_48px.png");
        bntCancel.setBackground(new Color(51, 51, 51));
        bntCancel.setIcon(close);
    }//GEN-LAST:event_bntCancelMouseExited

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ChangePass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ChangePass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ChangePass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ChangePass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                ChangePass dialog = new ChangePass(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntCancel;
    private javax.swing.JButton bntChange;
    private javax.swing.JButton bntReset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLbTK;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txtConfirmPass;
    private javax.swing.JPasswordField txtCurrent_Pass;
    private javax.swing.JPasswordField txtNewPass;
    // End of variables declaration//GEN-END:variables
}
