/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import DBModels.AdminDAO;
import DBModels.PlayerDAO;
import DBEntities.Admin;
import DBEntities.Player;
import java.awt.Color;
import java.util.ArrayList;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO
 */
public class Edit_Admin extends javax.swing.JDialog {

    ArrayList<Admin> ds;
    int D, M, Y;
    /**
     * Creates new form EditAdmin
     */
    private Admin_page Adm;

    public Edit_Admin(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Adm = (Admin_page) parent;
        Y = D = M = 0;
        System.out.println(Adm.user);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        bntcancel = new javax.swing.JButton();
        bntEdit = new javax.swing.JButton();
        bntreset = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cmbDay = new javax.swing.JComboBox<>();
        cmbMo = new javax.swing.JComboBox<>();
        cmbYear = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Email:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 140, 40));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Ngày Tháng Năm Sinh:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 190, 40));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Số Điện Thoại:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 120, 40));
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 370, 40));
        jPanel1.add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 370, 40));

        bntcancel.setBackground(new java.awt.Color(51, 51, 51));
        bntcancel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bntcancel.setForeground(new java.awt.Color(255, 255, 255));
        bntcancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel2.png"))); // NOI18N
        bntcancel.setText("Bỏ Qua");
        bntcancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bntcancelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bntcancelMouseExited(evt);
            }
        });
        bntcancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntcancelActionPerformed(evt);
            }
        });
        jPanel1.add(bntcancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 330, 160, 50));

        bntEdit.setBackground(new java.awt.Color(51, 51, 51));
        bntEdit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bntEdit.setForeground(new java.awt.Color(255, 255, 255));
        bntEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/OK Hand Medium Skin Tone_48px.png"))); // NOI18N
        bntEdit.setText("Thay Đổi");
        bntEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bntEditMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bntEditMouseExited(evt);
            }
        });
        bntEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntEditActionPerformed(evt);
            }
        });
        jPanel1.add(bntEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 170, 50));

        bntreset.setBackground(new java.awt.Color(51, 51, 51));
        bntreset.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bntreset.setForeground(new java.awt.Color(255, 255, 255));
        bntreset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reset_48px.png"))); // NOI18N
        bntreset.setText("Đặt Lại");
        bntreset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bntresetMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bntresetMouseExited(evt);
            }
        });
        bntreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntresetActionPerformed(evt);
            }
        });
        jPanel1.add(bntreset, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, 160, 50));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ĐỔI THÔNG TIN");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 390, 60));

        cmbDay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jPanel1.add(cmbDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 100, 40));

        cmbMo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        jPanel1.add(cmbMo, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, 90, 40));

        cmbYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010" }));
        jPanel1.add(cmbYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 180, 100, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 664, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bntEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntEditActionPerformed
        // TODO add your handling code here:
        boolean isOK = true;
        Admin Ad = new Admin();
        Ad.Name = Adm.user;
        Ad.Email = txtEmail.getText();
        Ad.Phone = txtPhone.getText();
        Ad.DOB = cmbDay.getSelectedItem().toString() + "-" + cmbMo.getSelectedItem().toString() + "-" + cmbYear.getSelectedItem().toString();
        ds = new AdminDAO().getList();
        for (Admin item : ds) {

            if (item.getEmail().equals(txtEmail.getText().trim()) && !item.getName().equals(Adm.user)) {
                JOptionPane.showMessageDialog(this, "Email này đã tồn tại. Vui lòng nhập lại!!! ");
                txtEmail.requestFocus();
                isOK = false;
                break;
            }
            if (item.getPhone().equals(txtPhone.getText().trim()) && !item.getName().equals(Adm.user)) {
                JOptionPane.showMessageDialog(this, "Số điện thoại này đã tồn tại. Vui lòng nhập lại!!! ");
                txtPhone.requestFocus();
                isOK = false;
                break;
            }
        }
        if (isOK == true && checkValid()) {
            int option = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn thay đổi thông tin trên....", "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (option == JOptionPane.YES_OPTION) {
                AdminDAO.changeAdmin(Ad);
                JOptionPane.showMessageDialog(this, "Đổi thông tin thành công...");
                this.dispose();

            }
        }


    }//GEN-LAST:event_bntEditActionPerformed

    private void bntresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntresetActionPerformed
        // TODO add your handling code here:
        txtEmail.setText(null);
        txtPhone.setText(null);
        cmbYear.setSelectedItem(null);
        cmbDay.setSelectedItem(null);
        cmbMo.setSelectedItem(null);
    }//GEN-LAST:event_bntresetActionPerformed

    private void bntcancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntcancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_bntcancelActionPerformed

    private void bntEditMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntEditMouseEntered
        // TODO add your handling code here:
        ImageIcon close = new ImageIcon("./src/images/OK Hand Light Skin Tone_48px.png");
        bntEdit.setBackground(Color.black);
        bntEdit.setIcon(close);
    }//GEN-LAST:event_bntEditMouseEntered

    private void bntEditMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntEditMouseExited
        // TODO add your handling code here:
        ImageIcon close = new ImageIcon("./src/images/OK Hand Medium Skin Tone_48px.png");
        bntEdit.setBackground(new Color(51, 51, 51));
        bntEdit.setIcon(close);
    }//GEN-LAST:event_bntEditMouseExited

    private void bntresetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntresetMouseEntered
        // TODO add your handling code here:
        ImageIcon close = new ImageIcon("./src/images/reset2.png");
        bntreset.setBackground(Color.black);
        bntreset.setIcon(close);
    }//GEN-LAST:event_bntresetMouseEntered

    private void bntresetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntresetMouseExited
        // TODO add your handling code here:
        ImageIcon close = new ImageIcon("./src/images/reset_48px.png");
        bntreset.setBackground(new Color(51, 51, 51));
        bntreset.setIcon(close);
    }//GEN-LAST:event_bntresetMouseExited

    private void bntcancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntcancelMouseEntered
        // TODO add your handling code here:
         ImageIcon close = new ImageIcon("./src/images/cancel_48px.png");
        bntcancel.setBackground(Color.black);
        bntcancel.setIcon(close);
    }//GEN-LAST:event_bntcancelMouseEntered

    private void bntcancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntcancelMouseExited
        // TODO add your handling code here:
            ImageIcon close = new ImageIcon("./src/images/cancel2.png");
        bntcancel.setBackground(new Color(51, 51, 51));
        bntcancel.setIcon(close);
    }//GEN-LAST:event_bntcancelMouseExited

    private boolean checkValid() {

        if (cmbDay.getSelectedIndex() != 0) {
            D = Integer.parseInt(cmbDay.getSelectedItem().toString());
        }
        if (cmbMo.getSelectedIndex() != 0) {
            M = Integer.parseInt(cmbMo.getSelectedItem().toString());
        }
        if (cmbYear.getSelectedIndex() != 0) {
            Y = Integer.parseInt(cmbYear.getSelectedItem().toString());
        }

        Pattern Pm = Pattern.compile("^[a-zA-Z][\\w-]+@([\\w]+\\.[\\w]+|[\\w]+\\.[\\w]{2,}\\.[\\w]{2,})$");
        Matcher mm = Pm.matcher(txtEmail.getText().trim());
        if (!mm.matches()) {
            JOptionPane.showMessageDialog(this, "Email không hợp lệ... ");
            txtEmail.requestFocus();
            return false;
        }
        if (cmbDay.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn ngày sinh ...");
            return false;
        }
        if (cmbMo.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Vui lòng chon tháng sinh...");
            return false;
        }
        if (cmbYear.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "vui  lòng chon năm sinh...");
            return false;
        }

        if ((M == 4 || M == 6 || M == 9 || M == 11) && (D == 31)) {
            JOptionPane.showMessageDialog(this, "Tháng " + cmbMo.getSelectedItem() + " chỉ 30 Ngày");
            return false;
        }
        if (((Y % 4 == 0 && Y % 100 != 0) || (Y % 400 == 0)) && (M == 2 && D >= 29)) {
            JOptionPane.showMessageDialog(this, "Tháng 2 năm nhuận chỉ 28 ngày");
            return false;
        }
        if (M == 2 && D >= 30) {
            JOptionPane.showMessageDialog(this, "Tháng 2 chỉ 29 Ngày");
            return false;
        }
        Pattern p = Pattern.compile("[0-9]{10,12}");
        Matcher m = p.matcher(txtPhone.getText().trim());
        if (!m.matches()) {
            JOptionPane.showMessageDialog(this, "Số điện thoại không được để trống, phải là số và từ 10-12 ký số ... ");
            txtPhone.requestFocus();
            return false;
        }
        return true;
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Edit_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Edit_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Edit_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Edit_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Edit_Admin dialog = new Edit_Admin(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntEdit;
    private javax.swing.JButton bntcancel;
    private javax.swing.JButton bntreset;
    public javax.swing.JComboBox<String> cmbDay;
    public javax.swing.JComboBox<String> cmbMo;
    public javax.swing.JComboBox<String> cmbYear;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField txtEmail;
    public javax.swing.JTextField txtPhone;
    // End of variables declaration//GEN-END:variables
}
