/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import DBModels.HelpSupportDAO;
import DBEntities.Admin;
import DBEntities.HelpSupport;
import DBConnection.MyLib;
import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author LENOVO
 */
public final class HelpSupport_Admin_Detail extends javax.swing.JDialog {

    ArrayList<HelpSupport> ds;

    ArrayList<HelpSupport> DS;
    public int ID;
    /**
     * Creates new form HelpSupport_Admin_Detail
     *
     */
    private HelpSupport_Admin hp;

    public HelpSupport_Admin_Detail(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        hp = (HelpSupport_Admin) parent;
        view(hp.id);

    }

    public void view(int id) {
        ID = id;
        // HelpSupport HelpSupport = new HelpSupport();
        ds = new HelpSupportDAO().getview();
        for (HelpSupport item : ds) {
            if (item.getCaseid() == id) {
                System.out.println(id);
                lbfrom.setText(item.getName());
                lbtitle.setText(item.casetitle);
                txtconten.setText(item.messages);
                if (item.getIMage() != null) {
              ImageIcon img = new ImageIcon(item.getIMage());
              Image im = img.getImage();
//                    lbimage.setIcon(img);
                 //String str = new String(item.getImage());
                 //  BufferedImage image = ImageIO.read(new File(filename));
                 
                // ImageIcon icon = new ImageIcon(item.getImage().getScaledInstance(110, 100, item.getImage().SCALE_SMOOTH));
               //  Bo im rder border = BorderFactory.createLineBorder(Color.black, 1);
                 lbimage.setIcon(new ImageIcon(fitimage(im, 230, 230)));
             //    lbtitle.setBorder(border);
                }
                break;
            }
        }

    }
     private Image fitimage(Image img, int w, int h) {
        BufferedImage resizedimage = new BufferedImage(w, h, BufferedImage.TYPE_INT_RGB);
        Graphics2D g2 = resizedimage.createGraphics();
        g2.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BILINEAR);
        g2.drawImage(img, 0, 0, w, h, null);
        g2.dispose();
        return resizedimage;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbtitle = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbimage = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        lbfrom = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtconten = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Hình Ảnh");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 160, 100, 30));

        lbtitle.setBackground(new java.awt.Color(255, 255, 255));
        lbtitle.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbtitle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbtitle.setOpaque(true);
        jPanel1.add(lbtitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 540, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 0));
        jLabel3.setText("THÔNG TIN PHẢN HỒI CHI TIẾT");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 370, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Tài khoản:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, 100, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Tiêu Đề:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 80, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Nội Dung:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 100, 30));

        lbimage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153)));
        lbimage.setOpaque(true);
        jPanel1.add(lbimage, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 200, 230, 210));

        jButton1.setBackground(new java.awt.Color(51, 153, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton1.setText("Tải Hình Ảnh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 440, 230, 40));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/strop2.png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 490, 110, 110));

        lbfrom.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbfrom.setForeground(new java.awt.Color(0, 102, 102));
        lbfrom.setText("d");
        jPanel1.add(lbfrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, 210, 30));

        txtconten.setColumns(20);
        txtconten.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        txtconten.setLineWrap(true);
        txtconten.setRows(5);
        txtconten.setWrapStyleWord(true);
        txtconten.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtconten.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtcontenMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(txtconten);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 690, 280));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/NenXanhLa2.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 610));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1025, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 613, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        HelpSupport HP = new HelpSupport();
        DS = new HelpSupportDAO().Downlimg();
        for(HelpSupport item:DS){
            if(ID==item.getCaseid()){
                try {
                    try (FileOutputStream fileOutputStream = new FileOutputStream("./src/HPImages/"+ item.getCaseid()+".png")) {
                        fileOutputStream.write(item.getIMage());
                        fileOutputStream.close();
                         JOptionPane.showMessageDialog(this, "Tải hình thành công.");
                    }
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(HelpSupport_Admin_Detail.class.getName()).log(Level.SEVERE, null, ex);
                    
                } catch (IOException ex) {
                    Logger.getLogger(HelpSupport_Admin_Detail.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                break;
            }
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtcontenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtcontenMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcontenMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HelpSupport_Admin_Detail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HelpSupport_Admin_Detail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HelpSupport_Admin_Detail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HelpSupport_Admin_Detail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                HelpSupport_Admin_Detail dialog = new HelpSupport_Admin_Detail(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbfrom;
    private javax.swing.JLabel lbimage;
    private javax.swing.JLabel lbtitle;
    private javax.swing.JTextArea txtconten;
    // End of variables declaration//GEN-END:variables
}
