package View;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import DBEntities.vwHighScore;
import DBModels.HighScoreDAO;
import View.*;
import java.awt.*;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ThienKim
 */
public class HighScore extends javax.swing.JFrame {

    Settings setting = new Settings();
    Home home = new Home();
    public HighScore() {
        initComponents();
        Showprofile();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Top3Date = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        Top3Score = new javax.swing.JLabel();
        Top1ID = new javax.swing.JLabel();
        Top2ID = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        Top1Scen = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        Top1Score = new javax.swing.JLabel();
        Top2Score = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        Top1Date = new javax.swing.JLabel();
        Top2Date = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        Top2Scen = new javax.swing.JLabel();
        Top3Scen = new javax.swing.JLabel();
        Top4ID = new javax.swing.JLabel();
        Top5ID = new javax.swing.JLabel();
        Top4Scen = new javax.swing.JLabel();
        Top5Scen = new javax.swing.JLabel();
        Top5Score = new javax.swing.JLabel();
        Top4Score = new javax.swing.JLabel();
        Top4Date = new javax.swing.JLabel();
        Top5Date = new javax.swing.JLabel();
        Top8Date = new javax.swing.JLabel();
        Top9Date = new javax.swing.JLabel();
        Top7Date = new javax.swing.JLabel();
        Top6Date = new javax.swing.JLabel();
        Top7Score = new javax.swing.JLabel();
        Top6Score = new javax.swing.JLabel();
        Top8Score = new javax.swing.JLabel();
        Top9Score = new javax.swing.JLabel();
        Top9Scen = new javax.swing.JLabel();
        Top8Scen = new javax.swing.JLabel();
        Top7Scen = new javax.swing.JLabel();
        Top6Scen = new javax.swing.JLabel();
        Top6ID = new javax.swing.JLabel();
        Top7ID = new javax.swing.JLabel();
        Top8ID = new javax.swing.JLabel();
        Top9ID = new javax.swing.JLabel();
        Top3ID = new javax.swing.JLabel();
        Top10ID = new javax.swing.JLabel();
        Top10Scen = new javax.swing.JLabel();
        Top10Score = new javax.swing.JLabel();
        Top10Date = new javax.swing.JLabel();
        Back = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocationByPlatform(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(1, 21, 45));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1470, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1470, 10));

        jPanel1.setBackground(new java.awt.Color(1, 21, 45));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1470, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 780, 1470, 10));

        jPanel3.setBackground(new java.awt.Color(138, 207, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Arial", 0, 60)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_crown_100px.png"))); // NOI18N
        jLabel6.setText("Điểm cao");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, 420, 80));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_crown_70px.png"))); // NOI18N
        jLabel3.setPreferredSize(new java.awt.Dimension(100, 100));
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 70, 70));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_crown_100px_3.png"))); // NOI18N
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 100, 60));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_crown_80px.png"))); // NOI18N
        jLabel10.setPreferredSize(new java.awt.Dimension(100, 100));
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 80, 50));

        jLabel2.setFont(new java.awt.Font("MS PMincho", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("10");
        jLabel2.setPreferredSize(new java.awt.Dimension(100, 100));
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 690, 90, 50));

        jLabel4.setFont(new java.awt.Font("MS PMincho", 1, 36)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("4");
        jLabel4.setPreferredSize(new java.awt.Dimension(100, 100));
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 70, 50));

        jLabel5.setFont(new java.awt.Font("MS PMincho", 1, 36)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("5");
        jLabel5.setPreferredSize(new java.awt.Dimension(100, 100));
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, 70, 50));

        jLabel7.setFont(new java.awt.Font("MS PMincho", 1, 36)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("6");
        jLabel7.setPreferredSize(new java.awt.Dimension(100, 100));
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 450, 70, 50));

        jLabel8.setFont(new java.awt.Font("MS PMincho", 1, 36)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("7");
        jLabel8.setPreferredSize(new java.awt.Dimension(100, 100));
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 510, 70, 50));

        jLabel11.setFont(new java.awt.Font("MS PMincho", 1, 36)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("8");
        jLabel11.setPreferredSize(new java.awt.Dimension(100, 100));
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 570, 70, 50));

        jLabel12.setFont(new java.awt.Font("MS PMincho", 1, 36)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("9");
        jLabel12.setPreferredSize(new java.awt.Dimension(100, 100));
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 630, 90, 50));

        Top3Date.setFont(new java.awt.Font("MS PMincho", 1, 36)); // NOI18N
        Top3Date.setForeground(new java.awt.Color(255, 255, 255));
        Top3Date.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Top3Date.setPreferredSize(new java.awt.Dimension(200, 40));
        jPanel3.add(Top3Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 280, 350, 40));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Xếp hạng");
        jLabel14.setPreferredSize(new java.awt.Dimension(200, 40));
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 210, -1));

        Top3Score.setFont(new java.awt.Font("MS PMincho", 1, 36)); // NOI18N
        Top3Score.setForeground(new java.awt.Color(255, 255, 255));
        Top3Score.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Top3Score.setPreferredSize(new java.awt.Dimension(200, 40));
        jPanel3.add(Top3Score, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 280, 210, 40));

        Top1ID.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        Top1ID.setForeground(new java.awt.Color(255, 255, 255));
        Top1ID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Top1ID.setPreferredSize(new java.awt.Dimension(200, 40));
        jPanel3.add(Top1ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 290, -1));

        Top2ID.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        Top2ID.setForeground(new java.awt.Color(255, 255, 255));
        Top2ID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Top2ID.setPreferredSize(new java.awt.Dimension(200, 40));
        jPanel3.add(Top2ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 290, -1));

        jLabel25.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Màn chơi");
        jLabel25.setPreferredSize(new java.awt.Dimension(200, 40));
        jPanel3.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 90, 180, -1));

        Top1Scen.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        Top1Scen.setForeground(new java.awt.Color(255, 255, 255));
        Top1Scen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Top1Scen.setPreferredSize(new java.awt.Dimension(200, 40));
        jPanel3.add(Top1Scen, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 160, 180, -1));

        jLabel31.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("Số điểm");
        jLabel31.setPreferredSize(new java.awt.Dimension(200, 40));
        jPanel3.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 90, 210, 40));

        Top1Score.setFont(new java.awt.Font("MS PMincho", 1, 36)); // NOI18N
        Top1Score.setForeground(new java.awt.Color(255, 255, 255));
        Top1Score.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Top1Score.setPreferredSize(new java.awt.Dimension(200, 40));
        jPanel3.add(Top1Score, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 160, 210, 40));

        Top2Score.setFont(new java.awt.Font("MS PMincho", 1, 36)); // NOI18N
        Top2Score.setForeground(new java.awt.Color(255, 255, 255));
        Top2Score.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Top2Score.setPreferredSize(new java.awt.Dimension(200, 40));
        jPanel3.add(Top2Score, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 220, 210, 40));

        jLabel34.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setText("Ngày chơi");
        jLabel34.setPreferredSize(new java.awt.Dimension(200, 40));
        jPanel3.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 90, 350, 40));

        Top1Date.setFont(new java.awt.Font("MS PMincho", 1, 36)); // NOI18N
        Top1Date.setForeground(new java.awt.Color(255, 255, 255));
        Top1Date.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Top1Date.setPreferredSize(new java.awt.Dimension(200, 40));
        jPanel3.add(Top1Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 160, 350, 40));

        Top2Date.setFont(new java.awt.Font("MS PMincho", 1, 36)); // NOI18N
        Top2Date.setForeground(new java.awt.Color(255, 255, 255));
        Top2Date.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Top2Date.setPreferredSize(new java.awt.Dimension(200, 40));
        jPanel3.add(Top2Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 220, 350, 40));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("ID người chơi");
        jLabel16.setPreferredSize(new java.awt.Dimension(200, 40));
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 210, -1));

        Top2Scen.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        Top2Scen.setForeground(new java.awt.Color(255, 255, 255));
        Top2Scen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Top2Scen.setPreferredSize(new java.awt.Dimension(200, 40));
        jPanel3.add(Top2Scen, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 220, 180, -1));

        Top3Scen.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        Top3Scen.setForeground(new java.awt.Color(255, 255, 255));
        Top3Scen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Top3Scen.setPreferredSize(new java.awt.Dimension(200, 40));
        jPanel3.add(Top3Scen, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 280, 180, -1));

        Top4ID.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        Top4ID.setForeground(new java.awt.Color(255, 255, 255));
        Top4ID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Top4ID.setPreferredSize(new java.awt.Dimension(200, 40));
        jPanel3.add(Top4ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 340, 290, -1));

        Top5ID.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        Top5ID.setForeground(new java.awt.Color(255, 255, 255));
        Top5ID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Top5ID.setPreferredSize(new java.awt.Dimension(200, 40));
        jPanel3.add(Top5ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 400, 290, -1));

        Top4Scen.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        Top4Scen.setForeground(new java.awt.Color(255, 255, 255));
        Top4Scen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Top4Scen.setPreferredSize(new java.awt.Dimension(200, 40));
        jPanel3.add(Top4Scen, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 340, 180, -1));

        Top5Scen.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        Top5Scen.setForeground(new java.awt.Color(255, 255, 255));
        Top5Scen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Top5Scen.setPreferredSize(new java.awt.Dimension(200, 40));
        jPanel3.add(Top5Scen, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 400, 180, -1));

        Top5Score.setFont(new java.awt.Font("MS PMincho", 1, 36)); // NOI18N
        Top5Score.setForeground(new java.awt.Color(255, 255, 255));
        Top5Score.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Top5Score.setPreferredSize(new java.awt.Dimension(200, 40));
        jPanel3.add(Top5Score, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 400, 210, 40));

        Top4Score.setFont(new java.awt.Font("MS PMincho", 1, 36)); // NOI18N
        Top4Score.setForeground(new java.awt.Color(255, 255, 255));
        Top4Score.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Top4Score.setPreferredSize(new java.awt.Dimension(200, 40));
        jPanel3.add(Top4Score, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 340, 210, 40));

        Top4Date.setFont(new java.awt.Font("MS PMincho", 1, 36)); // NOI18N
        Top4Date.setForeground(new java.awt.Color(255, 255, 255));
        Top4Date.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Top4Date.setPreferredSize(new java.awt.Dimension(200, 40));
        jPanel3.add(Top4Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 340, 350, 40));

        Top5Date.setFont(new java.awt.Font("MS PMincho", 1, 36)); // NOI18N
        Top5Date.setForeground(new java.awt.Color(255, 255, 255));
        Top5Date.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Top5Date.setPreferredSize(new java.awt.Dimension(200, 40));
        jPanel3.add(Top5Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 400, 350, 40));

        Top8Date.setFont(new java.awt.Font("MS PMincho", 1, 36)); // NOI18N
        Top8Date.setForeground(new java.awt.Color(255, 255, 255));
        Top8Date.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Top8Date.setPreferredSize(new java.awt.Dimension(200, 40));
        jPanel3.add(Top8Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 580, 350, 40));

        Top9Date.setFont(new java.awt.Font("MS PMincho", 1, 36)); // NOI18N
        Top9Date.setForeground(new java.awt.Color(255, 255, 255));
        Top9Date.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Top9Date.setPreferredSize(new java.awt.Dimension(200, 40));
        jPanel3.add(Top9Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 640, 350, 40));

        Top7Date.setFont(new java.awt.Font("MS PMincho", 1, 36)); // NOI18N
        Top7Date.setForeground(new java.awt.Color(255, 255, 255));
        Top7Date.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Top7Date.setPreferredSize(new java.awt.Dimension(200, 40));
        jPanel3.add(Top7Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 520, 350, 40));

        Top6Date.setFont(new java.awt.Font("MS PMincho", 1, 36)); // NOI18N
        Top6Date.setForeground(new java.awt.Color(255, 255, 255));
        Top6Date.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Top6Date.setPreferredSize(new java.awt.Dimension(200, 40));
        jPanel3.add(Top6Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 460, 350, 40));

        Top7Score.setFont(new java.awt.Font("MS PMincho", 1, 36)); // NOI18N
        Top7Score.setForeground(new java.awt.Color(255, 255, 255));
        Top7Score.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Top7Score.setPreferredSize(new java.awt.Dimension(200, 40));
        jPanel3.add(Top7Score, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 520, 210, 40));

        Top6Score.setFont(new java.awt.Font("MS PMincho", 1, 36)); // NOI18N
        Top6Score.setForeground(new java.awt.Color(255, 255, 255));
        Top6Score.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Top6Score.setPreferredSize(new java.awt.Dimension(200, 40));
        jPanel3.add(Top6Score, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 460, 210, 40));

        Top8Score.setFont(new java.awt.Font("MS PMincho", 1, 36)); // NOI18N
        Top8Score.setForeground(new java.awt.Color(255, 255, 255));
        Top8Score.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Top8Score.setPreferredSize(new java.awt.Dimension(200, 40));
        jPanel3.add(Top8Score, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 580, 210, 40));

        Top9Score.setFont(new java.awt.Font("MS PMincho", 1, 36)); // NOI18N
        Top9Score.setForeground(new java.awt.Color(255, 255, 255));
        Top9Score.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Top9Score.setPreferredSize(new java.awt.Dimension(200, 40));
        jPanel3.add(Top9Score, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 640, 210, 40));

        Top9Scen.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        Top9Scen.setForeground(new java.awt.Color(255, 255, 255));
        Top9Scen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Top9Scen.setPreferredSize(new java.awt.Dimension(200, 40));
        jPanel3.add(Top9Scen, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 640, 180, -1));

        Top8Scen.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        Top8Scen.setForeground(new java.awt.Color(255, 255, 255));
        Top8Scen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Top8Scen.setPreferredSize(new java.awt.Dimension(200, 40));
        jPanel3.add(Top8Scen, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 580, 180, -1));

        Top7Scen.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        Top7Scen.setForeground(new java.awt.Color(255, 255, 255));
        Top7Scen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Top7Scen.setPreferredSize(new java.awt.Dimension(200, 40));
        jPanel3.add(Top7Scen, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 520, 180, -1));

        Top6Scen.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        Top6Scen.setForeground(new java.awt.Color(255, 255, 255));
        Top6Scen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Top6Scen.setPreferredSize(new java.awt.Dimension(200, 40));
        jPanel3.add(Top6Scen, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 460, 180, -1));

        Top6ID.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        Top6ID.setForeground(new java.awt.Color(255, 255, 255));
        Top6ID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Top6ID.setPreferredSize(new java.awt.Dimension(200, 40));
        jPanel3.add(Top6ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 460, 290, -1));

        Top7ID.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        Top7ID.setForeground(new java.awt.Color(255, 255, 255));
        Top7ID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Top7ID.setPreferredSize(new java.awt.Dimension(200, 40));
        jPanel3.add(Top7ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 520, 290, -1));

        Top8ID.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        Top8ID.setForeground(new java.awt.Color(255, 255, 255));
        Top8ID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Top8ID.setPreferredSize(new java.awt.Dimension(200, 40));
        jPanel3.add(Top8ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 580, 290, -1));

        Top9ID.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        Top9ID.setForeground(new java.awt.Color(255, 255, 255));
        Top9ID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Top9ID.setPreferredSize(new java.awt.Dimension(200, 40));
        jPanel3.add(Top9ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 640, 290, -1));

        Top3ID.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        Top3ID.setForeground(new java.awt.Color(255, 255, 255));
        Top3ID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Top3ID.setPreferredSize(new java.awt.Dimension(200, 40));
        jPanel3.add(Top3ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, 290, -1));

        Top10ID.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        Top10ID.setForeground(new java.awt.Color(255, 255, 255));
        Top10ID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Top10ID.setPreferredSize(new java.awt.Dimension(200, 40));
        jPanel3.add(Top10ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 700, 290, -1));

        Top10Scen.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        Top10Scen.setForeground(new java.awt.Color(255, 255, 255));
        Top10Scen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Top10Scen.setPreferredSize(new java.awt.Dimension(200, 40));
        jPanel3.add(Top10Scen, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 700, 180, -1));

        Top10Score.setFont(new java.awt.Font("MS PMincho", 1, 36)); // NOI18N
        Top10Score.setForeground(new java.awt.Color(255, 255, 255));
        Top10Score.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Top10Score.setPreferredSize(new java.awt.Dimension(200, 40));
        jPanel3.add(Top10Score, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 700, 210, 40));

        Top10Date.setFont(new java.awt.Font("MS PMincho", 1, 36)); // NOI18N
        Top10Date.setForeground(new java.awt.Color(255, 255, 255));
        Top10Date.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Top10Date.setPreferredSize(new java.awt.Dimension(200, 40));
        jPanel3.add(Top10Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 700, 350, 40));

        Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_undo_80px_2.png"))); // NOI18N
        Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackMouseClicked(evt);
            }
        });
        jPanel3.add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1470, 770));

        setSize(new java.awt.Dimension(1472, 791));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    static boolean maximized = true;
    int xx, xy;
    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        // TODO add your handling code here:
        //drag this pane
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        // TODO add your handling code here:

        //source to drag
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void BackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseClicked
        // TODO add your handling code here:
        this.hide();
    }//GEN-LAST:event_BackMouseClicked

    public void ssetColor(JPanel p) {
        p.setBackground(new Color(92, 92, 92));
    }

    public void rreesetColor(JPanel p1) {
        p1.setBackground(new Color(75, 143, 121));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HighScore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HighScore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HighScore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HighScore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HighScore().setVisible(true);
            }
        });
    }

    private void setColor(JPanel pane) {
        pane.setBackground(new Color(41, 57, 80));
    }

    private void resetColor(JPanel[] pane, JPanel[] indicators) {
        for (int i = 0; i < pane.length; i++) {
            pane[i].setBackground(new Color(1, 21, 45));

        }
        for (int i = 0; i < indicators.length; i++) {
            indicators[i].setOpaque(false);
        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Back;
    private javax.swing.JLabel Top10Date;
    private javax.swing.JLabel Top10ID;
    private javax.swing.JLabel Top10Scen;
    private javax.swing.JLabel Top10Score;
    private javax.swing.JLabel Top1Date;
    private javax.swing.JLabel Top1ID;
    private javax.swing.JLabel Top1Scen;
    private javax.swing.JLabel Top1Score;
    private javax.swing.JLabel Top2Date;
    private javax.swing.JLabel Top2ID;
    private javax.swing.JLabel Top2Scen;
    private javax.swing.JLabel Top2Score;
    private javax.swing.JLabel Top3Date;
    private javax.swing.JLabel Top3ID;
    private javax.swing.JLabel Top3Scen;
    private javax.swing.JLabel Top3Score;
    private javax.swing.JLabel Top4Date;
    private javax.swing.JLabel Top4ID;
    private javax.swing.JLabel Top4Scen;
    private javax.swing.JLabel Top4Score;
    private javax.swing.JLabel Top5Date;
    private javax.swing.JLabel Top5ID;
    private javax.swing.JLabel Top5Scen;
    private javax.swing.JLabel Top5Score;
    private javax.swing.JLabel Top6Date;
    private javax.swing.JLabel Top6ID;
    private javax.swing.JLabel Top6Scen;
    private javax.swing.JLabel Top6Score;
    private javax.swing.JLabel Top7Date;
    private javax.swing.JLabel Top7ID;
    private javax.swing.JLabel Top7Scen;
    private javax.swing.JLabel Top7Score;
    private javax.swing.JLabel Top8Date;
    private javax.swing.JLabel Top8ID;
    private javax.swing.JLabel Top8Scen;
    private javax.swing.JLabel Top8Score;
    private javax.swing.JLabel Top9Date;
    private javax.swing.JLabel Top9ID;
    private javax.swing.JLabel Top9Scen;
    private javax.swing.JLabel Top9Score;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
ArrayList<vwHighScore> ds;

    private void Showprofile() {
        ds = new HighScoreDAO().getList();
        // SimpleDateFormat ft = new SimpleDateFormat ("yyyy.MM.dd hh:mm:ss");
        for (vwHighScore item : ds) {
            if (item.getRank() == 1) {
                Top1ID.setText(item.getPlayerID());
                Top1Scen.setText(String.valueOf(item.getquesId()));
                Top1Date.setText(String.valueOf(item.getPlayedDate()));
                Top1Score.setText(String.valueOf(item.getPlayerScore()));
            }
            if (item.getRank() == 2) {
                Top2ID.setText(item.getPlayerID());
                Top2Scen.setText(String.valueOf(item.getquesId()));
                Top2Date.setText(String.valueOf(item.getPlayedDate()));
                Top2Score.setText(String.valueOf(item.getPlayerScore()));
            }
            if (item.getRank() == 3) {
                Top3ID.setText(item.getPlayerID());
                Top3Scen.setText(String.valueOf(item.getquesId()));
                Top3Date.setText(String.valueOf(item.getPlayedDate()));
                Top3Score.setText(String.valueOf(item.getPlayerScore()));
            }
            if (item.getRank() == 4) {
                Top4ID.setText(item.getPlayerID());
                Top4Scen.setText(String.valueOf(item.getquesId()));
                Top4Date.setText(String.valueOf(item.getPlayedDate()));
                Top4Score.setText(String.valueOf(item.getPlayerScore()));
            }
            if (item.getRank() == 5) {
                Top5ID.setText(item.getPlayerID());
                Top5Scen.setText(String.valueOf(item.getquesId()));
                Top5Date.setText(String.valueOf(item.getPlayedDate())); // ft.format(item.getPlayedDate())
                Top5Score.setText(String.valueOf(item.getPlayerScore()));
            }
            if (item.getRank() == 6) {
                Top6ID.setText(item.getPlayerID());
                Top6Scen.setText(String.valueOf(item.getquesId()));
                Top6Date.setText(String.valueOf(item.getPlayedDate()));
                Top6Score.setText(String.valueOf(item.getPlayerScore()));
            }
            if (item.getRank() == 7) {
                Top7ID.setText(item.getPlayerID());
                Top7Scen.setText(String.valueOf(item.getquesId()));
                Top7Date.setText(String.valueOf(item.getPlayedDate()));
                Top7Score.setText(String.valueOf(item.getPlayerScore()));
            }
            if (item.getRank() == 8) {
                Top8ID.setText(item.getPlayerID());
                Top8Scen.setText(String.valueOf(item.getquesId()));
                Top8Date.setText(String.valueOf(item.getPlayedDate()));
                Top8Score.setText(String.valueOf(item.getPlayerScore()));
            }
            if (item.getRank() == 9) {
                Top9ID.setText(item.getPlayerID());
                Top9Scen.setText(String.valueOf(item.getquesId()));
                Top9Date.setText(String.valueOf(item.getPlayedDate()));
                Top9Score.setText(String.valueOf(item.getPlayerScore()));
            }
            if (item.getRank() == 10) {
                Top10ID.setText(item.getPlayerID());
                Top10Scen.setText(String.valueOf(item.getquesId()));
                Top10Date.setText(String.valueOf(item.getPlayedDate())); 
                Top10Score.setText(String.valueOf(item.getPlayerScore()));
            }
        }
    }
}
