/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import jaco.mp3.player.MP3Player;
import java.awt.Color;
import java.awt.GraphicsEnvironment;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author ThienKim
 */
public class Home extends javax.swing.JFrame {
    Notice note = new Notice();
//    HighScore highScore = new HighScore();
    Settings setting = new Settings();
    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
//        playmp3.play();
        // chưa lặp lại nhạc được
    }

    public static final String INTRO = "./src/mp3/Hello.mp3";
    MP3Player playmp3 = new MP3Player(new File(INTRO));
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        close = new javax.swing.JLabel();
        minimizer = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnplay = new javax.swing.JLabel();
        HuongDan = new javax.swing.JLabel();
        DiemCao = new javax.swing.JLabel();
        Cuahang = new javax.swing.JLabel();
        highscores = new javax.swing.JLabel();
        cuaHang = new javax.swing.JLabel();
        CaiDat = new javax.swing.JLabel();
        settings = new javax.swing.JLabel();
        Music = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocationByPlatform(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(1, 21, 45));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_delete_35px.png"))); // NOI18N
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });

        minimizer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_subtract_35px.png"))); // NOI18N
        minimizer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizerMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(1372, Short.MAX_VALUE)
                .addComponent(minimizer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(close)
                .addGap(21, 21, 21))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(minimizer, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(close))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1470, 60));

        jPanel3.setPreferredSize(new java.awt.Dimension(1470, 855));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnplay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/S5-copy.png"))); // NOI18N
        btnplay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnplayMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnplayMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnplayMouseExited(evt);
            }
        });
        jPanel3.add(btnplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 530, -1, -1));

        HuongDan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/S6-copy.png"))); // NOI18N
        HuongDan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HuongDanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HuongDanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HuongDanMouseExited(evt);
            }
        });
        jPanel3.add(HuongDan, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 620, -1, -1));

        DiemCao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DiemCao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_leaderboard_80px_1.png"))); // NOI18N
        DiemCao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DiemCaoMouseClicked(evt);
            }
        });
        jPanel3.add(DiemCao, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 760, 98, 50));

        Cuahang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Online_Store_80px_1.png"))); // NOI18N
        Cuahang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CuahangMouseClicked(evt);
            }
        });
        jPanel3.add(Cuahang, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 750, -1, 64));

        highscores.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        highscores.setForeground(new java.awt.Color(255, 255, 255));
        highscores.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        highscores.setText("ĐIỂM CAO");
        highscores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                highscoresMouseClicked(evt);
            }
        });
        jPanel3.add(highscores, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 820, -1, -1));

        cuaHang.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        cuaHang.setForeground(new java.awt.Color(255, 255, 255));
        cuaHang.setText("CỬA HÀNG");
        cuaHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cuaHangMouseClicked(evt);
            }
        });
        jPanel3.add(cuaHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, 820, -1, -1));

        CaiDat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_more_80px.png"))); // NOI18N
        CaiDat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CaiDatMouseClicked(evt);
            }
        });
        jPanel3.add(CaiDat, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 740, -1, -1));

        settings.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        settings.setForeground(new java.awt.Color(255, 255, 255));
        settings.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        settings.setText("THÔNG TIN");
        settings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                settingsMouseClicked(evt);
            }
        });
        jPanel3.add(settings, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 820, 120, 30));

        Music.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_music_80px.png"))); // NOI18N
        Music.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MusicMouseClicked(evt);
            }
        });
        jPanel3.add(Music, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 770, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Home-1.jpg"))); // NOI18N
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1470, 850));

        jPanel1.setBackground(new java.awt.Color(1, 21, 45));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1470, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 910, 1470, 40));

        setSize(new java.awt.Dimension(1472, 948));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    static boolean maximized =true;
    int xx,xy;
    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        // TODO add your handling code here:
        //drag this pane
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        // TODO add your handling code here:
        
        //source to drag
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xx,y-xy);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        // TODO add your handling code here:
        // dispose();
        System.exit(0);
    }//GEN-LAST:event_closeMouseClicked

    private void minimizerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizerMouseClicked
        // TODO add your handling code here: 
        Home.this.setExtendedState(this.getExtendedState() | this.ICONIFIED);
    }//GEN-LAST:event_minimizerMouseClicked
    
    
    private void HuongDanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HuongDanMouseClicked
        // TODO add your handling code here:
        note.setVisible(true);
    }//GEN-LAST:event_HuongDanMouseClicked

//    Login lg = new Login();
    private void btnplayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnplayMouseClicked
        // TODO add your handling code here:
//       lg.setVisible(true);
    }//GEN-LAST:event_btnplayMouseClicked

    private void btnplayMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnplayMouseEntered
        // TODO add your handling code here:
//        ImageIcon close = new ImageIcon("./images/S5-copy1.png");
//        btnplay.setIcon(close);
    }//GEN-LAST:event_btnplayMouseEntered

    private void btnplayMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnplayMouseExited
        // TODO add your handling code here:
//        ImageIcon close = new ImageIcon("./images/S5-copy.png");
//        btnplay.setIcon(close);
    }//GEN-LAST:event_btnplayMouseExited

    private void HuongDanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HuongDanMouseEntered
        // TODO add your handling code here:
//        ImageIcon close = new ImageIcon("./images/S6-copy1.png");
//        HuongDan.setIcon(close);
    }//GEN-LAST:event_HuongDanMouseEntered

    private void HuongDanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HuongDanMouseExited
        // TODO add your handling code here:
//        ImageIcon close = new ImageIcon("./images/S6-copy.png");
//        HuongDan.setIcon(close);
    }//GEN-LAST:event_HuongDanMouseExited

    private void CaiDatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CaiDatMouseClicked
        // TODO add your handling code here:
        setting.setVisible(true);
    }//GEN-LAST:event_CaiDatMouseClicked

    private void settingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsMouseClicked
        // TODO add your handling code here:
        setting.setVisible(true);
    }//GEN-LAST:event_settingsMouseClicked

    private void DiemCaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DiemCaoMouseClicked
        // TODO add your handling code here:
//        highScore.setVisible(true);
    }//GEN-LAST:event_DiemCaoMouseClicked

    private void highscoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_highscoresMouseClicked
        // TODO add your handling code here:
//        highScore.setVisible(true);
    }//GEN-LAST:event_highscoresMouseClicked

    private void CuahangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CuahangMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_CuahangMouseClicked

    private void cuaHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cuaHangMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_cuaHangMouseClicked

    private void MusicMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MusicMouseClicked
        playmp3.pause();
//        ImageIcon close = new ImageIcon("./images/audio.png");
//        Music.setIcon(close);
    }//GEN-LAST:event_MusicMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CaiDat;
    private javax.swing.JLabel Cuahang;
    private javax.swing.JLabel DiemCao;
    private javax.swing.JLabel HuongDan;
    private javax.swing.JLabel Music;
    private javax.swing.JLabel btnplay;
    private javax.swing.JLabel close;
    private javax.swing.JLabel cuaHang;
    private javax.swing.JLabel highscores;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel minimizer;
    private javax.swing.JLabel settings;
    // End of variables declaration//GEN-END:variables
}