package View;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import View.*;
import java.awt.*;
import javax.swing.*;

/**
 *
 * @author ThienKim
 */
public class Settings extends javax.swing.JFrame {

    public Settings() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        back = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnDG = new javax.swing.JLabel();
        btnHD = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocationByPlatform(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(1, 21, 45));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 10));

        jPanel3.setBackground(new java.awt.Color(138, 207, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_undo_80px_2.png"))); // NOI18N
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        jPanel3.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Thông tin");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        btnDG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/DG.png"))); // NOI18N
        btnDG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDGMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDGMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDGMouseExited(evt);
            }
        });
        jPanel3.add(btnDG, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, -1, -1));

        btnHD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/HD.png"))); // NOI18N
        btnHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHDMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHDMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHDMouseExited(evt);
            }
        });
        jPanel3.add(btnHD, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 600, 270));

        jPanel2.setBackground(new java.awt.Color(1, 21, 45));
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 620, 10));

        jPanel5.setBackground(new java.awt.Color(1, 21, 45));
        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 0, -1, 280));

        jPanel4.setBackground(new java.awt.Color(1, 21, 45));
        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, 270));

        setSize(new java.awt.Dimension(620, 289));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        // TODO add your handling code here:
        this.hide();
    }//GEN-LAST:event_backMouseClicked

    private void btnHDMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHDMouseEntered
        // TODO add your handling code here:
//        ImageIcon close = new ImageIcon("D:\\AptechSem2\\Project Sem2\\Project\\source\\Player\\src\\start\\images\\HD1.png");
//        btnHD.setIcon(close);
    }//GEN-LAST:event_btnHDMouseEntered

    private void btnHDMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHDMouseExited
        // TODO add your handling code here:
//        ImageIcon close = new ImageIcon("D:\\AptechSem2\\Project Sem2\\Project\\source\\Player\\src\\start\\images\\HD.png");
//        btnHD.setIcon(close);
    }//GEN-LAST:event_btnHDMouseExited

    private void btnDGMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDGMouseEntered
        // TODO add your handling code here:
//        ImageIcon close = new ImageIcon("D:\\AptechSem2\\Project Sem2\\Project\\source\\Player\\src\\start\\images\\DG1.png");
//        btnDG.setIcon(close);
    }//GEN-LAST:event_btnDGMouseEntered

    private void btnDGMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDGMouseExited
        // TODO add your handling code here:
//        ImageIcon close = new ImageIcon("D:\\AptechSem2\\Project Sem2\\Project\\source\\Player\\src\\start\\images\\DG.png");
//        btnDG.setIcon(close);
    }//GEN-LAST:event_btnDGMouseExited
Notice note = new Notice();
    private void btnHDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHDMouseClicked
        // TODO add your handling code here:
        note.setVisible(true);
    }//GEN-LAST:event_btnHDMouseClicked
//HelpSupport help = new HelpSupport();
    private void btnDGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDGMouseClicked
        // TODO add your handling code here:
//        help.setVisible(true);
    }//GEN-LAST:event_btnDGMouseClicked

    static boolean maximized =true;
    int xx,xy;
    
    public void ssetColor(JPanel p){
        p.setBackground(new Color(92,92,92));
    }
    public void rreesetColor(JPanel p1){
        p1.setBackground(new Color(75,143,121));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Settings().setVisible(true);
            }
        });
    }
   
    
    private void setColor(JPanel pane)
    {
        pane.setBackground(new Color(41,57,80));
    }
    
    private void resetColor(JPanel [] pane, JPanel [] indicators)
    {
        for(int i=0;i<pane.length;i++){
           pane[i].setBackground(new Color(1,21,45));
           
        } for(int i=0;i<indicators.length;i++){
           indicators[i].setOpaque(false);           
        }
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JLabel btnDG;
    private javax.swing.JLabel btnHD;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}